# PART 1: NP ARRAY, ARANGE, ZEROS, ONES, LINSPACE, IDENTITY

In [1]:
import numpy as np

In [2]:
angka = [1,2,3] # ini list
angkanp = np.array(angka)
print(type(angkanp))

angkanp*3

<class 'numpy.ndarray'>


array([3, 6, 9])

In [3]:
list2D = [[1,2,3],[4,5,6],[7,8,9]]
array2D = np.array(list2D)

array2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Np Arange
arange = np.arange(1,10) #start, end
arange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Np zeros
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [6]:
#Np ones baris x kolom
np.ones((2,4)) #kurung double

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
#Np linspace start, end (include), dibagi jadi berapa
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [8]:
#identity matrix diagonalnya 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# PART 2: RAND, RANDN, RANDINT, RESHAPE, ARGMAX, INDEXING 1D, SLICING 2D

In [9]:
# Bilangan distribusi uniform dari 0 - 1 (RAND)
np.random.rand(7)

array([0.39110452, 0.47246659, 0.57087749, 0.81850076, 0.80094806,
       0.97145257, 0.1921692 ])

In [10]:
np.random.rand(5,4) # baris x kolom

array([[0.19878997, 0.8141067 , 0.18552762, 0.443214  ],
       [0.81751906, 0.91397763, 0.87309471, 0.88362241],
       [0.58758109, 0.39276599, 0.94677557, 0.35461201],
       [0.43077815, 0.3378346 , 0.18978019, 0.55250444],
       [0.06407032, 0.37165141, 0.74056518, 0.2355108 ]])

In [11]:
# Distribusi normal (gaussian) (RANDN)
np.random.randn(2,4)

array([[-0.42093209,  0.33745245, -0.45694916, -0.17303626],
       [-0.2925248 , -0.30457474, -0.86023222,  0.27017232]])

In [12]:
# Random integer (RANDINT)
randint = np.random.randint(1,11,20) #start, end (not included), berapa jumlahnya
randint = randint.reshape(5,4) # harus di definisikan ulang supaya reshape nya berhasil
randint.reshape(4,5) # kalau cuman seperti ini cuman menunjukkan ilustrasi
randint

array([[ 2,  7,  4,  9],
       [ 1,  1,  3,  7],
       [ 1,  4,  6,  1],
       [ 6,  3,  9, 10],
       [ 7,  4,  1,  9]])

In [13]:
randint2 = randint.reshape(2,10)
randint2

array([[ 2,  7,  4,  9,  1,  1,  3,  7,  1,  4],
       [ 6,  1,  6,  3,  9, 10,  7,  4,  1,  9]])

In [14]:
coba1d = np.random.randint(1,100,20)
coba2d = np.random.randint(1,100,20).reshape(4,5)

In [15]:
coba1d

array([19, 40,  5, 27, 66, 90, 40, 52, 36, 58, 82, 51, 75, 94, 53, 50, 60,
       43, 65, 28])

In [16]:
coba1d.max()

94

In [17]:
coba2d

array([[ 9, 78, 79, 15, 20],
       [80, 42, 57, 14, 98],
       [40, 36, 84, 68, 79],
       [59, 78, 21, 80, 89]])

In [18]:
coba2d.max()

98

In [19]:
# argmax untuk mencari index value terbesar (index mulai dari 0)
coba1d.argmax()

13

In [20]:
# argmax 2d dihitung mendatar bukan baris x kolom. dihitung dari pojok kiri atas
coba2d.argmax()

9

In [21]:
# shape tanpa tanda kurung
coba1d.shape

(20,)

In [22]:
arrayX = np.arange(0,11)
array_X_copy = arrayX.copy() # selalu pakai copy ketika mau mengubah array supaya aman
arrayX

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# indexing
arrayX2 = arrayX[:6]
arrayX2

array([0, 1, 2, 3, 4, 5])

In [24]:
arrayX2[:] = 100

In [25]:
# hati hati slicing Array Numpy karena akan nge link dengan array sebelumnya
# index 0-5 jadi 100 value nya 
arrayX

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [26]:
array_X_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# slicing array 2d
list = [[1,2,3],[4,5,6]]
array2d_list = np.array(list)
array2d_list

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
array2d_list[1,2]

6

In [29]:
array2d_list[1:2,1:]

array([[5, 6]])

# PART 3: OPERASI MATEMATIKA

In [30]:
array_y = np.arange(0,11)
array_y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
array_y + 5 # INGAT KALAU SEPERTI INI PREVIEW SAJA KARENA BELUM DI ASSIGN VARIABLE

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
listA = [1,2,3]
listA + listA

[1, 2, 3, 1, 2, 3]

In [33]:
array_listA = np.array(listA)
array_listA + array_listA

array([2, 4, 6])

In [34]:
1/array_y # ADA WARNING TAPI TETAP DI EKSEKUSI SELAGI ADA NILAI YANG BISA DIOLAH

<ipython-input-34-2d309d5d78fd>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/array_y # ADA WARNING TAPI TETAP DI EKSEKUSI SELAGI ADA NILAI YANG BISA DIOLAH


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [35]:
np.sqrt(array_y)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [36]:
np.exp(array_y) # bilangan pangkat e

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [37]:
array_y.max() # INI FUNGSI NUMPY MAX

10

In [38]:
array_y.min()

0